name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-west-2
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: sns,s3,sqs
          DEBUG: 1
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        options: >-
          --health-cmd "curl -f http://localhost:4566/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 10s
          -v ${{ github.workspace }}/localstack:/etc/localstack/init/ready.d
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: camera_reel
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run tests
        run: cargo test
