name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-west-2
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: camera_reel
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: "latest"
          install-awslocal: "true"
          configuration: DEBUG=1,SERVICES=sns,s3,sqs

      - name: Setup AWS resources in LocalStack
        run: |
          # Create SNS topic
          awslocal sns create-topic --name events --region us-west-2
          # Create S3 bucket
          awslocal s3 mb s3://camera-reel
          awslocal s3api put-bucket-acl --bucket camera-reel --acl public-read

      - name: Run tests
        run: cargo test
