name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run tests 
        run: cargo test

